import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const roboto = Roboto({
  weight: ["400", "100", "300", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = cookies();
  const hh = data.get("hahaha")
  console.log(hh)
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        {children}
        </body>
    </html>
  );
}
